title: HTMLyrics
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :htmlyrics

social:
  twitter: _htmlyrics
  github: HTMLyrics

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
